version: '3.8'
services:
  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 4317:4317
    restart: always
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

