name: influxdb2
services:
  influxdb2:
    container_name: layer8-influxdb2
    image: influxdb:2
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb2-data:/var/lib/influxdb2
volumes:
  influxdb2-data:
